const { sequelize } = require('./config/db');
const { User, Restaurant, MenuItem, Collection, Offer, Order, Review, Reservation } = require('./models');
const bcrypt = require('bcryptjs');
require('dotenv').config();

const restaurants = [
  // --- Varanasi Restaurants ---
  {
    name: 'Baati Chokha',
    description: 'Authentic Banarasi cuisine with a rustic village ambiance. Famous for its baati chokha, litti, and traditional thalis.',
    cuisine: 'North Indian, Banarasi',
    address: 'D-58/18, Assi Ghat Road, Lanka',
    city: 'Varanasi',
    area: 'Lanka',
    phone: '9876543210',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    rating: 4.5,
    reviewCount: 342,
    priceRange: 'medium',
    costForTwo: 500,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '10:00',
    closingTime: '22:30',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3100,
    longitude: 82.9913,
    area: 'Lanka',
    deliveryRadius: 6,
  },
  {
    name: 'Canton Royale',
    description: 'Premium multi-cuisine restaurant offering Chinese, Thai, and Continental dishes with a rooftop view of the Ganges.',
    cuisine: 'Chinese, Thai, Continental',
    address: 'S-20/51, The Mall Road, Cantt',
    city: 'Varanasi',
    area: 'Cantt',
    phone: '9876543211',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
    rating: 4.3,
    reviewCount: 287,
    priceRange: 'high',
    costForTwo: 1200,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '11:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '35-45 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 25.2990,
    longitude: 82.9900,
    deliveryRadius: 7,
  },
  {
    name: 'Pizzeria Vaatika Cafe',
    description: 'Charming cafe near Assi Ghat serving wood-fired pizzas, pastas, and refreshing smoothies with Ganga views.',
    cuisine: 'Italian, Cafe, Pizza',
    address: 'B-1/158, Assi Ghat',
    city: 'Varanasi',
    area: 'Assi Ghat',
    phone: '9876543212',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    rating: 4.6,
    reviewCount: 523,
    priceRange: 'medium',
    costForTwo: 600,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '08:00',
    closingTime: '22:00',
    isOpen: true,
    deliveryTime: '25-35 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3176,
    longitude: 83.0068,
    deliveryRadius: 5,
  },
  {
    name: 'Kashi Chat Bhandar',
    description: 'Legendary street food spot in Godowlia. The best chaat, pani puri, and tamatar chaat in all of Varanasi.',
    cuisine: 'Street Food, Chaat',
    address: 'Godowlia Chowk, Near Vishwanath Gali',
    city: 'Varanasi',
    area: 'Godowlia',
    phone: '9876543213',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
    rating: 4.7,
    reviewCount: 892,
    priceRange: 'low',
    costForTwo: 150,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '10:00',
    closingTime: '21:00',
    isOpen: true,
    deliveryTime: '15-25 min',
    hasDelivery: true,
    hasDineIn: false,
    hasNightlife: false,
    latitude: 25.3350,
    longitude: 83.0050,
    deliveryRadius: 4,
  },
  {
    name: 'Tadka Restaurant',
    description: 'Popular family restaurant serving rich North Indian curries, biryanis, and tandoori specialties.',
    cuisine: 'North Indian, Mughlai, Biryani',
    address: 'Sigra Main Road, Near Sigra Stadium',
    city: 'Varanasi',
    area: 'Sigra',
    phone: '9876543214',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    rating: 4.2,
    reviewCount: 456,
    priceRange: 'medium',
    costForTwo: 700,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '11:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3050,
    longitude: 82.9870,
    deliveryRadius: 6,
  },
  {
    name: 'Brown Bread Bakery',
    description: 'European-style bakery and cafe near Dashashwamedh. Fresh breads, pastries, sandwiches and great coffee.',
    cuisine: 'Bakery, Cafe, Continental',
    address: 'D-33/68, Dashashwamedh Rd',
    city: 'Varanasi',
    area: 'Dashashwamedh',
    phone: '9876543215',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    rating: 4.4,
    reviewCount: 378,
    priceRange: 'medium',
    costForTwo: 450,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '07:00',
    closingTime: '21:00',
    isOpen: true,
    deliveryTime: '20-30 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3200,
    longitude: 83.0100,
    deliveryRadius: 5,
  },
  {
    name: 'The Crepe Factory',
    description: 'Quirky cafe serving sweet and savory crepes, waffles, shakes, and all-day breakfast near BHU.',
    cuisine: 'Cafe, Desserts, Continental',
    address: 'Near BHU Gate, Naria',
    city: 'Varanasi',
    area: 'BHU',
    phone: '9876543216',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    rating: 4.3,
    reviewCount: 267,
    priceRange: 'medium',
    costForTwo: 400,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '09:00',
    closingTime: '22:30',
    isOpen: true,
    deliveryTime: '20-30 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.2700,
    longitude: 82.9600,
    deliveryRadius: 5,
  },
  {
    name: 'Deena Chaat Bhandar',
    description: 'Iconic Varanasi street food since 1965. The OG tamatar chaat and tikki spot that locals swear by.',
    cuisine: 'Street Food, Chaat',
    address: 'Luxa Road, Near Godowlia',
    city: 'Varanasi',
    area: 'Luxa',
    phone: '9876543217',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=800',
    rating: 4.8,
    reviewCount: 1203,
    priceRange: 'low',
    costForTwo: 100,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '09:00',
    closingTime: '21:30',
    isOpen: true,
    deliveryTime: '15-20 min',
    hasDelivery: true,
    hasDineIn: false,
    hasNightlife: false,
    latitude: 25.3500,
    longitude: 83.0300,
    deliveryRadius: 4,
  },
  {
    name: 'Dosa Junction',
    description: 'South Indian heaven in Varanasi. Crispy dosas, fluffy idlis, steaming vadas with authentic sambar and chutneys.',
    cuisine: 'South Indian, Dosa',
    address: 'IP Mall, Sigra',
    city: 'Varanasi',
    area: 'Sigra',
    phone: '9876543218',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800',
    rating: 4.1,
    reviewCount: 198,
    priceRange: 'low',
    costForTwo: 250,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '08:00',
    closingTime: '22:00',
    isOpen: true,
    deliveryTime: '20-30 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.2850,
    longitude: 82.9850,
    deliveryRadius: 5,
  },
  {
    name: 'Shree Cafe',
    description: 'Trendy rooftop cafe overlooking the ghats. Great for Instagram-worthy sunsets with coffee, sandwiches and mocktails.',
    cuisine: 'Cafe, Italian, Fast Food',
    address: 'Meer Ghat, Near Dashashwamedh',
    city: 'Varanasi',
    area: 'Dashashwamedh',
    phone: '9876543219',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    rating: 4.4,
    reviewCount: 312,
    priceRange: 'medium',
    costForTwo: 550,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '07:30',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '25-35 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3150,
    longitude: 83.0050,
    deliveryRadius: 5,
  },
  {
    name: 'Hyderabad Biryani House',
    description: 'Aromatic dum biryanis cooked in authentic Hyderabadi style. Succulent kebabs and rich curries.',
    cuisine: 'Biryani, Mughlai, Hyderabadi',
    address: 'Lanka Crossing, BHU Road',
    city: 'Varanasi',
    area: 'Lanka',
    phone: '9876543220',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
    rating: 4.0,
    reviewCount: 267,
    priceRange: 'medium',
    costForTwo: 500,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '11:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '35-45 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3080,
    longitude: 82.9930,
    deliveryRadius: 7,
  },
  {
    name: 'The Great Kabab Factory',
    description: 'Premium kebab restaurant with unlimited kebab platters. A meat lover\'s paradise in the heart of Varanasi.',
    cuisine: 'Mughlai, Kebab, North Indian',
    address: 'Nadesar Palace Road',
    city: 'Varanasi',
    area: 'Nadesar',
    phone: '9876543221',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800',
    rating: 4.5,
    reviewCount: 189,
    priceRange: 'premium',
    costForTwo: 2000,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '12:00',
    closingTime: '23:30',
    isOpen: true,
    deliveryTime: '40-50 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 25.3250,
    longitude: 82.9800,
    deliveryRadius: 8,
  },
  {
    name: 'Malabar Cafe',
    description: 'Kerala-inspired cafe serving appam, puttu, fish curry and filter coffee. A taste of South India.',
    cuisine: 'South Indian, Kerala, Cafe',
    address: 'Mahmoorganj Main Road',
    city: 'Varanasi',
    area: 'Mahmoorganj',
    phone: '9876543222',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    rating: 4.2,
    reviewCount: 145,
    priceRange: 'medium',
    costForTwo: 400,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '07:00',
    closingTime: '21:30',
    isOpen: true,
    deliveryTime: '25-35 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.2950,
    longitude: 82.9700,
    deliveryRadius: 5,
  },
  {
    name: 'Burger Singh',
    description: 'Desi-style burgers with Indian spices and flavors. Loaded fries, shakes and quirky combos for the young crowd.',
    cuisine: 'Burgers, Fast Food, American',
    address: 'IP Mall, Ground Floor, Sigra',
    city: 'Varanasi',
    area: 'Sigra',
    phone: '9876543223',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    rating: 3.9,
    reviewCount: 234,
    priceRange: 'low',
    costForTwo: 350,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '10:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '20-30 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.2870,
    longitude: 82.9860,
    deliveryRadius: 6,
  },
  {
    name: 'Pepe\'s Kitchen',
    description: 'Mexican-inspired eatery with burritos, tacos, nachos and quesadillas. Student favorite near BHU campus.',
    cuisine: 'Mexican, Fast Food, Continental',
    address: 'Near BHU Lanka Gate',
    city: 'Varanasi',
    area: 'Lanka',
    phone: '9876543224',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    rating: 4.1,
    reviewCount: 178,
    priceRange: 'low',
    costForTwo: 300,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '10:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '20-25 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3120,
    longitude: 82.9890,
    deliveryRadius: 4,
  },
  {
    name: 'Ganga Fuji Restaurant',
    description: 'Japanese and Korean fusion restaurant with rooftop river views. Sushi, ramen, and bento boxes.',
    cuisine: 'Japanese, Korean, Asian',
    address: 'Assi Ghat Rd, Near Tulsi Ghat',
    city: 'Varanasi',
    area: 'Assi Ghat',
    phone: '9876543225',
    image: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800',
    rating: 4.3,
    reviewCount: 156,
    priceRange: 'high',
    costForTwo: 1000,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '11:30',
    closingTime: '22:30',
    isOpen: true,
    deliveryTime: '35-45 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3190,
    longitude: 83.0080,
    deliveryRadius: 5,
  },
  {
    name: 'Keshari Sweets',
    description: 'Iconic Varanasi sweet shop since 1940. Famous for rabri, malaiyo (winter special), kachori, and jalebi.',
    cuisine: 'Sweets, Street Food, Desserts',
    address: 'Chowk Main Road',
    city: 'Varanasi',
    area: 'Chowk',
    phone: '9876543226',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800',
    rating: 4.6,
    reviewCount: 734,
    priceRange: 'low',
    costForTwo: 200,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '06:00',
    closingTime: '22:00',
    isOpen: true,
    deliveryTime: '15-25 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3450,
    longitude: 83.0150,
    deliveryRadius: 5,
  },
  {
    name: 'Niyati Cafe & Lounge',
    description: 'Modern cafe and lounge with craft coffees, smoothie bowls, pastas and live music on weekends.',
    cuisine: 'Cafe, Continental, Italian',
    address: 'Bhelupur Crossing',
    city: 'Varanasi',
    area: 'Bhelupur',
    phone: '9876543227',
    image: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800',
    rating: 4.2,
    reviewCount: 198,
    priceRange: 'medium',
    costForTwo: 600,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '08:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '25-35 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 25.3100,
    longitude: 83.0000,
    deliveryRadius: 5,
  },
  {
    name: 'Sarnath Chinese Corner',
    description: 'Quick-service Chinese food stall near Sarnath. Momos, noodles, manchurian and fried rice specials.',
    cuisine: 'Chinese, Momos, Fast Food',
    address: 'Near Sarnath Buddhist Temple',
    city: 'Varanasi',
    area: 'Sarnath',
    phone: '9876543228',
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800',
    rating: 3.8,
    reviewCount: 123,
    priceRange: 'low',
    costForTwo: 200,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '10:00',
    closingTime: '22:00',
    isOpen: true,
    deliveryTime: '20-30 min',
    hasDelivery: true,
    hasDineIn: false,
    hasNightlife: false,
    latitude: 25.2800,
    longitude: 82.9950,
    deliveryRadius: 5,
  },
  {
    name: 'Pind Balluchi',
    description: 'Punjabi dhaba-style restaurant with butter chicken, dal makhani, laccha parantha and lassi.',
    cuisine: 'Punjabi, North Indian, Mughlai',
    address: 'Maldahiya Main Road',
    city: 'Varanasi',
    area: 'Maldahiya',
    phone: '9876543229',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800',
    rating: 4.0,
    reviewCount: 276,
    priceRange: 'medium',
    costForTwo: 600,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '11:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3400,
    longitude: 83.0200,
    deliveryRadius: 6,
  },
  {
    name: 'Flavours of China',
    description: 'Elegant Chinese restaurant with authentic Sichuan, Cantonese and Indo-Chinese dishes. Dragon rolls are a must try!',
    cuisine: 'Chinese, Asian',
    address: 'Kabir Chaura Road',
    city: 'Varanasi',
    area: 'Kabir Chaura',
    phone: '9876543230',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
    rating: 4.1,
    reviewCount: 209,
    priceRange: 'medium',
    costForTwo: 650,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '11:30',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.3300,
    longitude: 82.9950,
    deliveryRadius: 5,
  },
  {
    name: 'VNS Thali House',
    description: 'Unlimited Gujarati & Rajasthani thali at a fixed price. All-you-can-eat with 20+ items on the plate.',
    cuisine: 'Gujarati, Rajasthani, Thali',
    address: 'Pandeypur Main Road',
    city: 'Varanasi',
    area: 'Pandeypur',
    phone: '9876543231',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
    rating: 4.3,
    reviewCount: 345,
    priceRange: 'medium',
    costForTwo: 500,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '11:00',
    closingTime: '22:30',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.2600,
    longitude: 82.9500,
    deliveryRadius: 6,
  },
  {
    name: 'Tandoor Nights',
    description: 'Late-night tandoori and kebab specialist. Open till midnight. Reshmi kebab and roomali roti are legendary.',
    cuisine: 'Tandoor, North Indian, Kebab',
    address: 'Susuwahi Crossing',
    city: 'Varanasi',
    area: 'Susuwahi',
    phone: '9876543232',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    rating: 4.0,
    reviewCount: 187,
    priceRange: 'medium',
    costForTwo: 550,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '17:00',
    closingTime: '00:30',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 25.3150,
    longitude: 82.9750,
    deliveryRadius: 6,
  },
  {
    name: 'Green Leaf Vegan Kitchen',
    description: 'Varanasi\'s first 100% vegan restaurant. Plant-based bowls, smoothies, vegan desserts and herbal teas.',
    cuisine: 'Vegan, Healthy, Cafe',
    address: 'Near Shivpur Colony',
    city: 'Varanasi',
    area: 'Shivpur',
    phone: '9876543233',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    rating: 4.4,
    reviewCount: 98,
    priceRange: 'medium',
    costForTwo: 500,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '08:00',
    closingTime: '21:00',
    isOpen: true,
    deliveryTime: '20-30 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 25.2900,
    longitude: 83.0050,
    deliveryRadius: 5,
  },

  // --- Delhi Restaurants ---
  {
    name: 'Bukhara',
    description: 'Iconic restaurant at ITC Maurya known worldwide for its Dal Bukhara and tandoori dishes. A true Delhi institution.',
    cuisine: 'North Indian, Mughlai, Tandoor',
    address: 'ITC Maurya, Sardar Patel Marg, Diplomatic Enclave',
    city: 'Delhi',
    area: 'Connaught Place',
    phone: '9811000001',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    rating: 4.8,
    reviewCount: 1245,
    priceRange: 'premium',
    costForTwo: 5000,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '12:30',
    closingTime: '23:30',
    isOpen: true,
    deliveryTime: '45-55 min',
    hasDelivery: false,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 28.5977,
    longitude: 77.1730,
    deliveryRadius: 5,
  },
  {
    name: 'Paranthe Wali Gali',
    description: 'Famous lane in Old Delhi serving over 30 varieties of stuffed paranthas since 1872.',
    cuisine: 'Street Food, North Indian',
    address: 'Gali Paranthe Wali, Chandni Chowk',
    city: 'Delhi',
    area: 'Chandni Chowk',
    phone: '9811000002',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
    rating: 4.3,
    reviewCount: 876,
    priceRange: 'low',
    costForTwo: 200,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '08:00',
    closingTime: '22:00',
    isOpen: true,
    deliveryTime: '25-35 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 28.6562,
    longitude: 77.2300,
    deliveryRadius: 4,
  },
  {
    name: 'Social Hauz Khas',
    description: 'Trendy urban hangout with quirky interiors. Amazing cocktails, bar food, and great music evenings.',
    cuisine: 'Continental, Cafe, Bar Food',
    address: '9-A & 12, Hauz Khas Village',
    city: 'Delhi',
    area: 'Hauz Khas',
    phone: '9811000003',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    rating: 4.2,
    reviewCount: 1532,
    priceRange: 'high',
    costForTwo: 1800,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '12:00',
    closingTime: '01:00',
    isOpen: true,
    deliveryTime: '40-50 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 28.5494,
    longitude: 77.2001,
    deliveryRadius: 6,
  },
  {
    name: 'Saravana Bhavan',
    description: 'Legendary South Indian chain serving authentic dosas, idlis, and filter coffee in the heart of CP.',
    cuisine: 'South Indian, Vegetarian',
    address: 'P-13, Connaught Place',
    city: 'Delhi',
    area: 'Connaught Place',
    phone: '9811000004',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800',
    rating: 4.4,
    reviewCount: 654,
    priceRange: 'medium',
    costForTwo: 600,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '07:30',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 28.6315,
    longitude: 77.2167,
    deliveryRadius: 5,
  },
  {
    name: 'Cafe Delhi Heights',
    description: 'Popular casual dining chain with burgers, pasta, and all-day breakfast in a cozy setting.',
    cuisine: 'Cafe, Continental, Italian',
    address: 'N-3, Select Citywalk, Saket',
    city: 'Delhi',
    area: 'Saket',
    phone: '9811000005',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    rating: 4.1,
    reviewCount: 987,
    priceRange: 'medium',
    costForTwo: 1200,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '10:00',
    closingTime: '23:30',
    isOpen: true,
    deliveryTime: '35-45 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 28.5285,
    longitude: 77.2190,
    deliveryRadius: 7,
  },
  {
    name: 'Karim\'s',
    description: 'A 100-year-old institution near Jama Masjid serving the finest Mughlai cuisine. Legendary mutton burra and nihari.',
    cuisine: 'Mughlai, North Indian, Kebabs',
    address: '16, Gali Kababian, Jama Masjid',
    city: 'Delhi',
    area: 'Chandni Chowk',
    phone: '9811000006',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800',
    rating: 4.5,
    reviewCount: 2100,
    priceRange: 'medium',
    costForTwo: 800,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '09:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 28.6508,
    longitude: 77.2336,
    deliveryRadius: 5,
  },
  {
    name: 'PCO Bar',
    description: 'Speakeasy-style bar in Vasant Vihar with craft cocktails, dim lighting, and a secret entrance vibe.',
    cuisine: 'Continental, Bar Food',
    address: 'D-4, Vasant Vihar',
    city: 'Delhi',
    area: 'Vasant Kunj',
    phone: '9811000007',
    image: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
    rating: 4.3,
    reviewCount: 540,
    priceRange: 'high',
    costForTwo: 2500,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '17:00',
    closingTime: '01:00',
    isOpen: true,
    deliveryTime: null,
    hasDelivery: false,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 28.5557,
    longitude: 77.1564,
    deliveryRadius: 3,
  },
  {
    name: 'Rajinder da Dhaba',
    description: 'Iconic open-air dhaba in Safdarjung serving the best butter chicken and tandoori in Delhi.',
    cuisine: 'North Indian, Mughlai',
    address: 'A-1/2, Safdarjung Enclave Market',
    city: 'Delhi',
    area: 'Greater Kailash',
    phone: '9811000008',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    rating: 4.4,
    reviewCount: 1870,
    priceRange: 'medium',
    costForTwo: 700,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '16:00',
    closingTime: '01:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 28.5603,
    longitude: 77.1955,
    deliveryRadius: 5,
  },

  // --- Mumbai Restaurants ---
  {
    name: 'Leopold Cafe',
    description: 'Iconic 19th-century cafe in Colaba. A Mumbai landmark with multicuisine menu, cold beer, and vibrant atmosphere.',
    cuisine: 'Multi-Cuisine, Continental, Cafe',
    address: 'S.B. Singh Road, Colaba Causeway',
    city: 'Mumbai',
    area: 'Colaba',
    phone: '9822000001',
    image: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800',
    rating: 4.2,
    reviewCount: 3200,
    priceRange: 'medium',
    costForTwo: 1200,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '07:30',
    closingTime: '00:30',
    isOpen: true,
    deliveryTime: '40-50 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 18.9229,
    longitude: 72.8316,
    deliveryRadius: 5,
  },
  {
    name: 'Bademiya',
    description: 'Late-night seekh kebab legend near Colaba. Queues around midnight are a Mumbai rite of passage.',
    cuisine: 'Mughlai, Kebabs, Street Food',
    address: 'Tulloch Road, Behind Taj Mahal Hotel',
    city: 'Mumbai',
    area: 'Colaba',
    phone: '9822000002',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800',
    rating: 4.0,
    reviewCount: 1450,
    priceRange: 'low',
    costForTwo: 500,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '19:00',
    closingTime: '04:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: false,
    hasNightlife: true,
    latitude: 18.9218,
    longitude: 72.8335,
    deliveryRadius: 6,
  },
  {
    name: 'Bastian Bandra',
    description: 'Celeb-favourite seafood and Asian restaurant with gorgeous interiors and an extensive cocktail menu.',
    cuisine: 'Seafood, Asian, Continental',
    address: 'B/1 New Kamanwala Compound, Linking Road, Bandra West',
    city: 'Mumbai',
    area: 'Bandra',
    phone: '9822000003',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    rating: 4.5,
    reviewCount: 876,
    priceRange: 'premium',
    costForTwo: 4000,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '12:00',
    closingTime: '01:00',
    isOpen: true,
    deliveryTime: null,
    hasDelivery: false,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 19.0596,
    longitude: 72.8295,
    deliveryRadius: 5,
  },
  {
    name: 'Swati Snacks',
    description: 'Legendary Gujarati and Maharashtrian snacks joint. Panki, sev puri, and handvo are must-tries.',
    cuisine: 'Street Food, Gujarati, Maharashtrian',
    address: 'Karai Estate, Tardeo Road',
    city: 'Mumbai',
    area: 'Lower Parel',
    phone: '9822000004',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
    rating: 4.6,
    reviewCount: 1980,
    priceRange: 'low',
    costForTwo: 400,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '12:00',
    closingTime: '22:30',
    isOpen: true,
    deliveryTime: '25-35 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 18.9852,
    longitude: 72.8132,
    deliveryRadius: 5,
  },
  {
    name: 'Trishna',
    description: 'Renowned seafood restaurant in Fort famous for its butter garlic crab and Hyderabadi fish.',
    cuisine: 'Seafood, Coastal, South Indian',
    address: '7, Sai Baba Marg, Kala Ghoda, Fort',
    city: 'Mumbai',
    area: 'Fort',
    phone: '9822000005',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    rating: 4.4,
    reviewCount: 1120,
    priceRange: 'high',
    costForTwo: 2000,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '12:00',
    closingTime: '15:30',
    isOpen: true,
    deliveryTime: '35-45 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 18.9324,
    longitude: 72.8320,
    deliveryRadius: 5,
  },
  {
    name: 'Doolally Taproom',
    description: 'India\'s first craft beer bar with freshly brewed ales, great pizzas, and a chill rooftop in Andheri.',
    cuisine: 'Cafe, Pizza, Bar Food',
    address: 'Imperial Mahal, 5th Road, Khar West',
    city: 'Mumbai',
    area: 'Andheri',
    phone: '9822000006',
    image: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
    rating: 4.3,
    reviewCount: 765,
    priceRange: 'high',
    costForTwo: 1800,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '12:00',
    closingTime: '01:30',
    isOpen: true,
    deliveryTime: null,
    hasDelivery: false,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 19.0714,
    longitude: 72.8349,
    deliveryRadius: 4,
  },
  {
    name: 'Vada Pav Junction',
    description: 'Quick service joint with Mumbai\'s iconic vada pav in 10+ flavors — schezwan, cheese, and classic.',
    cuisine: 'Street Food, Fast Food',
    address: 'Station Road, Andheri West',
    city: 'Mumbai',
    area: 'Andheri',
    phone: '9822000007',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=800',
    rating: 4.1,
    reviewCount: 430,
    priceRange: 'low',
    costForTwo: 150,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '07:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '15-25 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 19.1197,
    longitude: 72.8464,
    deliveryRadius: 4,
  },
  {
    name: 'Pizza By The Bay',
    description: 'Seaside restaurant at Marine Drive with wood-fired pizzas and gorgeous sunset views.',
    cuisine: 'Italian, Pizza, Continental',
    address: '143, Soona Mahal, Marine Drive',
    city: 'Mumbai',
    area: 'Marine Lines',
    phone: '9822000008',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    rating: 4.2,
    reviewCount: 1340,
    priceRange: 'medium',
    costForTwo: 1000,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '11:00',
    closingTime: '23:30',
    isOpen: true,
    deliveryTime: '35-45 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 18.9432,
    longitude: 72.8234,
    deliveryRadius: 5,
  },

  // --- Bangalore Restaurants ---
  {
    name: 'MTR 1924',
    description: 'A century-old heritage restaurant serving authentic Karnataka cuisine. Famous for its masala dosa and filter coffee.',
    cuisine: 'South Indian, Karnataka',
    address: '14, Lalbagh Road, Basavanagudi',
    city: 'Bangalore',
    area: 'Basavanagudi',
    phone: '9900000001',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800',
    rating: 4.7,
    reviewCount: 2340,
    priceRange: 'medium',
    costForTwo: 400,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '06:30',
    closingTime: '21:00',
    isOpen: true,
    deliveryTime: '25-35 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 12.9500,
    longitude: 77.5850,
    deliveryRadius: 5,
  },
  {
    name: 'Toit Brewpub',
    description: 'Bangalore\'s most popular microbrewery in Indiranagar. Great craft beers, live music, and pub grub.',
    cuisine: 'Continental, Bar Food, Pizza',
    address: '298, 100 Feet Road, Indiranagar',
    city: 'Bangalore',
    area: 'Indiranagar',
    phone: '9900000002',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    rating: 4.5,
    reviewCount: 4500,
    priceRange: 'high',
    costForTwo: 1800,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '12:00',
    closingTime: '01:00',
    isOpen: true,
    deliveryTime: null,
    hasDelivery: false,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 12.9784,
    longitude: 77.6408,
    deliveryRadius: 4,
  },
  {
    name: 'Vidyarthi Bhavan',
    description: 'Since 1943 — legendary crispy masala dosa with coconut chutney. Always a queue, always worth it.',
    cuisine: 'South Indian, Street Food',
    address: '32, Gandhi Bazaar, Basavanagudi',
    city: 'Bangalore',
    area: 'Basavanagudi',
    phone: '9900000003',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800',
    rating: 4.6,
    reviewCount: 1870,
    priceRange: 'low',
    costForTwo: 200,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '06:30',
    closingTime: '20:00',
    isOpen: true,
    deliveryTime: '20-30 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 12.9443,
    longitude: 77.5729,
    deliveryRadius: 4,
  },
  {
    name: 'Windmills Craftworks',
    description: 'Craft brewery and kitchen in Whitefield with wood-fired pizzas, live music, and a gorgeous open-air setting.',
    cuisine: 'Continental, Italian, Brewery',
    address: '27/1, Pattandur Agrahara, Whitefield',
    city: 'Bangalore',
    area: 'Whitefield',
    phone: '9900000004',
    image: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
    rating: 4.3,
    reviewCount: 980,
    priceRange: 'high',
    costForTwo: 2200,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: true,
    hasOutdoorSeating: true,
    openingTime: '12:00',
    closingTime: '01:00',
    isOpen: true,
    deliveryTime: null,
    hasDelivery: false,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 12.9698,
    longitude: 77.7500,
    deliveryRadius: 4,
  },
  {
    name: 'Meghana Foods',
    description: 'Famous Andhra-style biryani chain. Their boneless chicken biryani is legendary across Bangalore.',
    cuisine: 'Biryani, Andhra, South Indian',
    address: '124, Koramangala 5th Block',
    city: 'Bangalore',
    area: 'Koramangala',
    phone: '9900000005',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
    rating: 4.4,
    reviewCount: 3200,
    priceRange: 'medium',
    costForTwo: 600,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '11:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 12.9352,
    longitude: 77.6245,
    deliveryRadius: 6,
  },
  {
    name: 'The Permit Room',
    description: 'Modern South Indian tapas bar on MG Road. Creative cocktails and deconstructed dosa tacos.',
    cuisine: 'South Indian Fusion, Bar, Cafe',
    address: '1st Floor, Devatha Plaza, MG Road',
    city: 'Bangalore',
    area: 'MG Road',
    phone: '9900000006',
    image: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800',
    rating: 4.3,
    reviewCount: 760,
    priceRange: 'high',
    costForTwo: 1600,
    isVeg: false,
    hasAlcohol: true,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '12:00',
    closingTime: '00:30',
    isOpen: true,
    deliveryTime: '35-45 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: true,
    latitude: 12.9756,
    longitude: 77.6066,
    deliveryRadius: 5,
  },
  {
    name: 'Corner House Ice Cream',
    description: 'Bangalore\'s beloved ice cream parlor since 1983. The Death By Chocolate is an absolute must-have.',
    cuisine: 'Desserts, Ice Cream',
    address: '15, Residency Road, Ashok Nagar',
    city: 'Bangalore',
    area: 'MG Road',
    phone: '9900000007',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
    rating: 4.5,
    reviewCount: 2450,
    priceRange: 'low',
    costForTwo: 300,
    isVeg: true,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: false,
    openingTime: '11:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '20-30 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 12.9699,
    longitude: 77.6083,
    deliveryRadius: 5,
  },
  {
    name: 'Truffles',
    description: 'Bangalore\'s favourite burger joint. Massive burgers, steaks, and amazing shakes in Koramangala.',
    cuisine: 'Burgers, American, Cafe',
    address: '28, St Marks Road, Koramangala',
    city: 'Bangalore',
    area: 'Koramangala',
    phone: '9900000008',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
    rating: 4.6,
    reviewCount: 5100,
    priceRange: 'medium',
    costForTwo: 800,
    isVeg: false,
    hasAlcohol: false,
    petFriendly: false,
    hasOutdoorSeating: true,
    openingTime: '11:00',
    closingTime: '23:00',
    isOpen: true,
    deliveryTime: '30-40 min',
    hasDelivery: true,
    hasDineIn: true,
    hasNightlife: false,
    latitude: 12.9345,
    longitude: 77.6159,
    deliveryRadius: 6,
  },
];

// Menu items keyed by restaurant index
const menuItemsByRestaurant = {
  0: [ // Baati Chokha
    { name: 'Baati Chokha Platter', description: 'Traditional wheat balls with roasted veggie mash, ghee and dal', price: 199, category: 'Main Course', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400' },
    { name: 'Litti Chokha', description: 'Stuffed wheat balls with sattu filling and chokha', price: 149, category: 'Main Course', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400' },
    { name: 'Banarasi Thali', description: 'Complete thali with dal, sabzi, roti, rice, raita, papad and dessert', price: 249, category: 'Main Course', isVeg: true, isBestseller: false, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400' },
    { name: 'Paneer Tikka', description: 'Marinated cottage cheese grilled in tandoor', price: 179, category: 'Starters', isVeg: true, isBestseller: false, image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400' },
    { name: 'Lassi', description: 'Thick creamy yogurt drink', price: 79, category: 'Beverages', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1626078299536-6c5b89567c5e?w=400' },
    { name: 'Thandai', description: 'Traditional Banarasi spiced milk with almonds and saffron', price: 99, category: 'Beverages', isVeg: true, isBestseller: false },
  ],
  1: [ // Canton Royale
    { name: 'Dragon Chicken', description: 'Crispy chicken tossed in fiery Chinese sauce', price: 349, category: 'Main Course', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=400' },
    { name: 'Thai Green Curry', description: 'Aromatic green curry with vegetables and jasmine rice', price: 299, category: 'Main Course', isVeg: false, isBestseller: false, image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400' },
    { name: 'Veg Manchurian', description: 'Deep fried veggie balls in tangy manchurian sauce', price: 219, category: 'Starters', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400' },
    { name: 'Pad Thai Noodles', description: 'Classic Thai stir fried rice noodles with peanuts', price: 269, category: 'Main Course', isVeg: false, isBestseller: false },
    { name: 'Dim Sum Basket', description: 'Steamed dumplings with dipping sauce (6 pcs)', price: 249, category: 'Starters', isVeg: false, isBestseller: false },
    { name: 'Chocolate Lava Cake', description: 'Warm gooey chocolate cake with vanilla ice cream', price: 199, category: 'Desserts', isVeg: true, isBestseller: true },
  ],
  2: [ // Pizzeria Vaatika
    { name: 'Margherita Pizza', description: 'Classic pizza with fresh mozzarella, tomato and basil', price: 249, category: 'Pizza', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400' },
    { name: 'BBQ Chicken Pizza', description: 'Smoky BBQ chicken with onions and peppers', price: 349, category: 'Pizza', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400' },
    { name: 'Pesto Pasta', description: 'Penne in homemade basil pesto cream sauce', price: 229, category: 'Pasta', isVeg: true, isBestseller: false, image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400' },
    { name: 'Garlic Bread', description: 'Crispy bread with garlic butter and herbs', price: 129, category: 'Sides', isVeg: true, isBestseller: false },
    { name: 'Cold Coffee', description: 'Chilled blended coffee with ice cream', price: 149, category: 'Beverages', isVeg: true, isBestseller: true },
    { name: 'Tiramisu', description: 'Classic Italian coffee-flavored dessert', price: 199, category: 'Desserts', isVeg: true, isBestseller: false },
  ],
  3: [ // Kashi Chat Bhandar
    { name: 'Tamatar Chaat', description: 'The legendary Banarasi tomato chaat with spices', price: 40, category: 'Chaat', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=400' },
    { name: 'Pani Puri', description: 'Crispy puris with spiced tamarind water (8 pcs)', price: 30, category: 'Chaat', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400' },
    { name: 'Aloo Tikki', description: 'Crispy potato patties with chutneys', price: 40, category: 'Chaat', isVeg: true, isBestseller: true },
    { name: 'Dahi Puri', description: 'Puris filled with yogurt, chutney and sev', price: 50, category: 'Chaat', isVeg: true, isBestseller: false },
    { name: 'Papdi Chaat', description: 'Crispy wafers with yogurt, chutneys and pomegranate', price: 50, category: 'Chaat', isVeg: true, isBestseller: false },
    { name: 'Matar Kulcha', description: 'Spiced green peas with crispy bread', price: 40, category: 'Snacks', isVeg: true, isBestseller: false },
  ],
  4: [ // Tadka Restaurant
    { name: 'Butter Chicken', description: 'Creamy tomato-based chicken curry', price: 299, category: 'Main Course', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400' },
    { name: 'Chicken Biryani', description: 'Fragrant basmati rice with spiced chicken', price: 279, category: 'Biryani', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400' },
    { name: 'Dal Makhani', description: 'Slow-cooked black lentils in butter and cream', price: 199, category: 'Main Course', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400' },
    { name: 'Paneer Butter Masala', description: 'Cottage cheese cubes in rich tomato gravy', price: 229, category: 'Main Course', isVeg: true, isBestseller: false },
    { name: 'Tandoori Roti', description: 'Whole wheat bread from tandoor', price: 25, category: 'Breads', isVeg: true, isBestseller: false },
    { name: 'Gulab Jamun', description: 'Deep-fried milk dumplings in sugar syrup', price: 89, category: 'Desserts', isVeg: true, isBestseller: false },
  ],
  5: [ // Brown Bread Bakery
    { name: 'Banana Walnut Cake', description: 'Moist cake with real banana and walnuts', price: 149, category: 'Cakes', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400' },
    { name: 'Club Sandwich', description: 'Triple-decker sandwich with veggies and cheese', price: 179, category: 'Sandwiches', isVeg: true, isBestseller: true },
    { name: 'Cappuccino', description: 'Rich espresso with steamed milk foam', price: 129, category: 'Beverages', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400' },
    { name: 'Croissant', description: 'Flaky French butter croissant', price: 99, category: 'Bakery', isVeg: true, isBestseller: false },
    { name: 'Chocolate Brownie', description: 'Dense fudgy chocolate brownie', price: 119, category: 'Desserts', isVeg: true, isBestseller: true },
    { name: 'Fresh Orange Juice', description: 'Freshly squeezed seasonal orange juice', price: 99, category: 'Beverages', isVeg: true, isBestseller: false },
  ],
  6: [ // The Crepe Factory
    { name: 'Nutella Banana Crepe', description: 'Warm crepe filled with Nutella and banana slices', price: 179, category: 'Sweet Crepes', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400' },
    { name: 'Chicken Tikka Crepe', description: 'Savory crepe with spiced chicken and veggies', price: 199, category: 'Savory Crepes', isVeg: false, isBestseller: true },
    { name: 'Belgian Waffle', description: 'Crispy waffle with maple syrup and butter', price: 149, category: 'Waffles', isVeg: true, isBestseller: false },
    { name: 'Mango Smoothie', description: 'Thick mango smoothie with cream', price: 129, category: 'Beverages', isVeg: true, isBestseller: true },
    { name: 'All Day Breakfast', description: 'Eggs, toast, beans, hash brown and juice', price: 229, category: 'Breakfast', isVeg: false, isBestseller: false },
    { name: 'Oreo Shake', description: 'Thick shake with crushed Oreo cookies', price: 149, category: 'Beverages', isVeg: true, isBestseller: false },
  ],
  7: [ // Deena Chaat Bhandar
    { name: 'Special Tamatar Chaat', description: 'Deena\'s signature tomato chaat — recipe unchanged since 1965', price: 50, category: 'Chaat', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=400' },
    { name: 'Aloo Tikki Chaat', description: 'Crispy potato tikki with curd, chutneys and sev', price: 50, category: 'Chaat', isVeg: true, isBestseller: true },
    { name: 'Ram Laddu', description: 'Fried moong dal fritters with radish chutney', price: 30, category: 'Snacks', isVeg: true, isBestseller: false },
    { name: 'Kachori Sabzi', description: 'Crispy kachori with spiced potato curry', price: 40, category: 'Snacks', isVeg: true, isBestseller: true },
    { name: 'Basket Chaat', description: 'Crispy potato basket filled with chaat masala mix', price: 50, category: 'Chaat', isVeg: true, isBestseller: false },
    { name: 'Jalebi', description: 'Hot crispy jalebi straight from the kadhai', price: 40, category: 'Sweets', isVeg: true, isBestseller: true },
  ],
};

// Generate menu items for remaining restaurants
const generateMenuItems = (restaurantIndex, cuisineType) => {
  const menus = {
    'South Indian': [
      { name: 'Masala Dosa', description: 'Crispy crepe filled with spiced potato', price: 99, category: 'Dosa', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=400' },
      { name: 'Idli Sambar', description: 'Steamed rice cakes with lentil soup', price: 79, category: 'Breakfast', isVeg: true, isBestseller: true },
      { name: 'Vada', description: 'Crispy lentil doughnuts with chutney', price: 69, category: 'Snacks', isVeg: true, isBestseller: false },
      { name: 'Uttapam', description: 'Thick savory pancake with toppings', price: 89, category: 'Breakfast', isVeg: true, isBestseller: false },
      { name: 'Filter Coffee', description: 'Authentic South Indian filter coffee', price: 49, category: 'Beverages', isVeg: true, isBestseller: true },
      { name: 'Rava Dosa', description: 'Crispy semolina crepe', price: 109, category: 'Dosa', isVeg: true, isBestseller: false },
    ],
    Biryani: [
      { name: 'Mutton Biryani', description: 'Slow-cooked dum biryani with tender mutton', price: 349, category: 'Biryani', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400' },
      { name: 'Chicken Biryani', description: 'Aromatic chicken dum biryani', price: 279, category: 'Biryani', isVeg: false, isBestseller: true },
      { name: 'Veg Biryani', description: 'Mixed vegetable biryani with raita', price: 199, category: 'Biryani', isVeg: true, isBestseller: false },
      { name: 'Seekh Kebab', description: 'Minced meat kebabs from charcoal grill', price: 229, category: 'Starters', isVeg: false, isBestseller: true },
      { name: 'Mirchi Ka Salan', description: 'Tangy peanut-sesame chili curry', price: 149, category: 'Sides', isVeg: true, isBestseller: false },
      { name: 'Phirni', description: 'Rice pudding dessert', price: 79, category: 'Desserts', isVeg: true, isBestseller: false },
    ],
    Burgers: [
      { name: 'Classic Smash Burger', description: 'Juicy smashed beef patty with cheese', price: 169, category: 'Burgers', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400' },
      { name: 'Paneer Tikka Burger', description: 'Spiced paneer patty in a brioche bun', price: 149, category: 'Burgers', isVeg: true, isBestseller: true },
      { name: 'Loaded Fries', description: 'Fries with cheese sauce, jalapenos and sour cream', price: 129, category: 'Sides', isVeg: true, isBestseller: true },
      { name: 'Chicken Wings', description: 'Spicy buffalo chicken wings (6 pcs)', price: 199, category: 'Sides', isVeg: false, isBestseller: false },
      { name: 'Oreo Milkshake', description: 'Thick oreo cookie milkshake', price: 149, category: 'Beverages', isVeg: true, isBestseller: false },
      { name: 'Churros', description: 'Cinnamon sugar churros with chocolate dip', price: 129, category: 'Desserts', isVeg: true, isBestseller: false },
    ],
    Mexican: [
      { name: 'Chicken Burrito', description: 'Stuffed flour tortilla with chicken, beans and salsa', price: 199, category: 'Burritos', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400' },
      { name: 'Nachos Supreme', description: 'Tortilla chips with cheese, beans, and sour cream', price: 179, category: 'Starters', isVeg: true, isBestseller: true },
      { name: 'Tacos (3 pcs)', description: 'Soft tacos with your choice of filling', price: 149, category: 'Tacos', isVeg: false, isBestseller: false },
      { name: 'Quesadilla', description: 'Grilled tortilla with melted cheese and veggies', price: 159, category: 'Main Course', isVeg: true, isBestseller: false },
      { name: 'Mexican Rice Bowl', description: 'Rice bowl with beans, salsa, cheese and guacamole', price: 179, category: 'Bowls', isVeg: true, isBestseller: false },
      { name: 'Churros', description: 'Cinnamon dusted churros with chocolate sauce', price: 99, category: 'Desserts', isVeg: true, isBestseller: false },
    ],
    Cafe: [
      { name: 'Espresso', description: 'Strong Italian espresso shot', price: 99, category: 'Coffee', isVeg: true, isBestseller: false },
      { name: 'Latte', description: 'Smooth espresso with steamed milk', price: 149, category: 'Coffee', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400' },
      { name: 'Panini', description: 'Grilled Italian sandwich with cheese and veggies', price: 179, category: 'Bites', isVeg: true, isBestseller: true },
      { name: 'Pasta Alfredo', description: 'Creamy white sauce pasta', price: 229, category: 'Main Course', isVeg: true, isBestseller: false },
      { name: 'Cheesecake', description: 'New York style baked cheesecake', price: 199, category: 'Desserts', isVeg: true, isBestseller: true },
      { name: 'Smoothie Bowl', description: 'Acai smoothie bowl with granola and fruits', price: 189, category: 'Healthy', isVeg: true, isBestseller: false },
    ],
    Kebab: [
      { name: 'Galouti Kebab', description: 'Melt-in-mouth minced meat kebabs', price: 299, category: 'Kebabs', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400' },
      { name: 'Reshmi Kebab', description: 'Silky chicken kebabs cream marinated', price: 279, category: 'Kebabs', isVeg: false, isBestseller: true },
      { name: 'Paneer Tikka', description: 'Tandoor-grilled cottage cheese cubes', price: 229, category: 'Kebabs', isVeg: true, isBestseller: false },
      { name: 'Biryani', description: 'Fragrant rice with tender meat', price: 299, category: 'Main Course', isVeg: false, isBestseller: true },
      { name: 'Roomali Roti', description: 'Paper-thin soft bread', price: 35, category: 'Breads', isVeg: true, isBestseller: false },
      { name: 'Shahi Tukda', description: 'Royal bread pudding with rabri', price: 149, category: 'Desserts', isVeg: true, isBestseller: false },
    ],
    Punjabi: [
      { name: 'Butter Chicken', description: 'Tender chicken in rich tomato-butter gravy', price: 299, category: 'Main Course', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400' },
      { name: 'Dal Makhani', description: 'Creamy black lentils slow-cooked overnight', price: 199, category: 'Main Course', isVeg: true, isBestseller: true },
      { name: 'Chole Bhature', description: 'Spiced chickpeas with fried bread', price: 149, category: 'Main Course', isVeg: true, isBestseller: true },
      { name: 'Laccha Parantha', description: 'Layered flaky bread from tandoor', price: 45, category: 'Breads', isVeg: true, isBestseller: false },
      { name: 'Lassi', description: 'Thick sweet Punjabi lassi', price: 79, category: 'Beverages', isVeg: true, isBestseller: true },
      { name: 'Jalebi with Rabri', description: 'Hot jalebi served with thickened milk', price: 99, category: 'Desserts', isVeg: true, isBestseller: false },
    ],
    Chinese: [
      { name: 'Chicken Momos', description: 'Steamed chicken dumplings (8 pcs)', price: 99, category: 'Momos', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400' },
      { name: 'Hakka Noodles', description: 'Stir-fried noodles with vegetables', price: 129, category: 'Noodles', isVeg: true, isBestseller: true },
      { name: 'Manchurian', description: 'Veg balls in spicy soy-based gravy', price: 149, category: 'Main Course', isVeg: true, isBestseller: false },
      { name: 'Fried Rice', description: 'Wok-tossed rice with egg and veggies', price: 139, category: 'Rice', isVeg: false, isBestseller: false },
      { name: 'Spring Rolls', description: 'Crispy rolls with vegetable filling', price: 99, category: 'Starters', isVeg: true, isBestseller: false },
      { name: 'Honey Chilli Potato', description: 'Crispy potatoes glazed in honey chilli sauce', price: 119, category: 'Starters', isVeg: true, isBestseller: true },
    ],
    Japanese: [
      { name: 'Salmon Sushi Roll', description: 'Fresh salmon maki roll (8 pcs)', price: 399, category: 'Sushi', isVeg: false, isBestseller: true, image: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=400' },
      { name: 'Tonkotsu Ramen', description: 'Rich pork bone broth ramen with chashu', price: 349, category: 'Ramen', isVeg: false, isBestseller: true },
      { name: 'Edamame', description: 'Steamed soybeans with sea salt', price: 149, category: 'Starters', isVeg: true, isBestseller: false },
      { name: 'Tempura', description: 'Crispy battered vegetables and shrimp', price: 299, category: 'Starters', isVeg: false, isBestseller: false },
      { name: 'Matcha Latte', description: 'Japanese green tea latte', price: 179, category: 'Beverages', isVeg: true, isBestseller: false },
      { name: 'Mochi Ice Cream', description: 'Japanese rice cake with ice cream filling', price: 149, category: 'Desserts', isVeg: true, isBestseller: true },
    ],
    Sweets: [
      { name: 'Banarasi Rabri', description: 'Thick sweetened milk with nuts and saffron', price: 80, category: 'Sweets', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400' },
      { name: 'Malaiyo', description: 'Fluffy milk foam dessert (winter special)', price: 60, category: 'Sweets', isVeg: true, isBestseller: true },
      { name: 'Kachori with Sabzi', description: 'Crispy fried pastry with potato curry', price: 40, category: 'Snacks', isVeg: true, isBestseller: true },
      { name: 'Jalebi', description: 'Crispy deep-fried sweet spirals', price: 60, category: 'Sweets', isVeg: true, isBestseller: true },
      { name: 'Peda', description: 'Traditional milk-based sweet', price: 50, category: 'Sweets', isVeg: true, isBestseller: false },
      { name: 'Thandai', description: 'Spiced cold milk with almonds', price: 70, category: 'Beverages', isVeg: true, isBestseller: false },
    ],
    Thali: [
      { name: 'Gujarati Thali', description: 'Unlimited Gujarati thali with 20+ items', price: 249, category: 'Thali', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400' },
      { name: 'Rajasthani Thali', description: 'Unlimited Rajasthani thali with dal baati', price: 269, category: 'Thali', isVeg: true, isBestseller: true },
      { name: 'Mini Thali', description: 'Compact thali with 8 items', price: 149, category: 'Thali', isVeg: true, isBestseller: false },
      { name: 'Buttermilk', description: 'Spiced chaas to go with your thali', price: 39, category: 'Beverages', isVeg: true, isBestseller: false },
      { name: 'Papad Basket', description: 'Assorted roasted and fried papads', price: 49, category: 'Extras', isVeg: true, isBestseller: false },
      { name: 'Gulab Jamun (2 pcs)', description: 'Hot gulab jamuns with thali', price: 49, category: 'Desserts', isVeg: true, isBestseller: false },
    ],
    Vegan: [
      { name: 'Buddha Bowl', description: 'Quinoa, roasted veggies, hummus, avocado', price: 249, category: 'Bowls', isVeg: true, isBestseller: true, image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400' },
      { name: 'Smoothie Bowl', description: 'Açaí, banana, granola, fresh fruits', price: 199, category: 'Bowls', isVeg: true, isBestseller: true },
      { name: 'Vegan Burger', description: 'Plant-based patty with vegan cheese', price: 199, category: 'Main Course', isVeg: true, isBestseller: false },
      { name: 'Herbal Tea', description: 'Organic chamomile or mint herbal tea', price: 99, category: 'Beverages', isVeg: true, isBestseller: false },
      { name: 'Avocado Toast', description: 'Sourdough with smashed avocado and seeds', price: 179, category: 'Breakfast', isVeg: true, isBestseller: true },
      { name: 'Raw Energy Bar', description: 'Dates, nuts, and cacao energy bar', price: 99, category: 'Desserts', isVeg: true, isBestseller: false },
    ],
  };

  const cuisineMap = {
    8: 'South Indian', 9: 'Cafe', 10: 'Biryani', 11: 'Kebab', 12: 'South Indian',
    13: 'Burgers', 14: 'Mexican', 15: 'Japanese', 16: 'Sweets', 17: 'Cafe',
    18: 'Chinese', 19: 'Punjabi', 20: 'Chinese', 21: 'Thali', 22: 'Kebab', 23: 'Vegan',
    // Delhi
    24: 'Kebab', 25: 'Punjabi', 26: 'Cafe', 27: 'South Indian', 28: 'Cafe', 29: 'Kebab', 30: 'Cafe', 31: 'Punjabi',
    // Mumbai
    32: 'Cafe', 33: 'Kebab', 34: 'Cafe', 35: 'South Indian', 36: 'Kebab', 37: 'Cafe', 38: 'South Indian', 39: 'Cafe',
    // Bangalore
    40: 'South Indian', 41: 'Cafe', 42: 'South Indian', 43: 'Cafe', 44: 'Biryani', 45: 'Cafe', 46: 'Sweets', 47: 'Burgers',
  };

  return menus[cuisineMap[restaurantIndex]] || menus['Cafe'];
};

const collections = [
  { title: 'Newly Opened', description: 'The latest additions to the food scene in Varanasi', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600', tag: 'new', placeCount: 8 },
  { title: 'Trending This Week', description: 'Popular restaurants everyone is talking about', image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600', tag: 'trending', placeCount: 12 },
  { title: 'Best Cafes', description: 'Top-rated cafes for your coffee fix and chill vibes', image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600', tag: 'cafe', placeCount: 10 },
  { title: 'Street Food Trail', description: 'Authentic street food that defines Varanasi', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600', tag: 'street_food', placeCount: 15 },
  { title: 'Romantic Dining', description: 'Perfect spots for date nights and special occasions', image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600', tag: 'romantic', placeCount: 7 },
  { title: 'Best Biryani', description: 'The finest biryani joints in the city', image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600', tag: 'biryani', placeCount: 9 },
  { title: 'Budget Eats Under ₹300', description: 'Great food without burning a hole in your pocket', image: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600', tag: 'budget', placeCount: 18 },
  { title: 'Rooftop Restaurants', description: 'Dine with a view — the best rooftop spots', image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600', tag: 'rooftop', placeCount: 6 },
];

const seedData = async () => {
  try {
    await sequelize.authenticate();
    console.log('Connected to database');

    // Sync all models
    await sequelize.sync({ alter: true });
    console.log('Database synced');

    // Check if data already exists
    const existingCount = await Restaurant.count();
    if (existingCount > 0) {
      console.log(`Database already has ${existingCount} restaurants. Skipping seed.`);
      console.log('To re-seed, delete all restaurants first.');
      process.exit(0);
    }

    // === SEED RESTAURANTS ===
    console.log('\nSeeding restaurants...');
    const createdRestaurants = await Restaurant.bulkCreate(restaurants);
    console.log(`  ✓ Created ${createdRestaurants.length} restaurants`);

    // === SEED MENU ITEMS ===
    console.log('\nSeeding menu items...');
    let totalMenuItems = 0;
    for (let i = 0; i < createdRestaurants.length; i++) {
      const rid = createdRestaurants[i].id;
      const items = menuItemsByRestaurant[i] || generateMenuItems(i);
      const menuData = items.map((item) => ({
        ...item,
        restaurantId: rid,
        isAvailable: true,
        isNew: Math.random() > 0.7,
        spiceLevel: ['mild', 'medium', 'hot'][Math.floor(Math.random() * 3)],
      }));
      await MenuItem.bulkCreate(menuData);
      totalMenuItems += menuData.length;
    }
    console.log(`  ✓ Created ${totalMenuItems} menu items`);

    // === SEED COLLECTIONS ===
    console.log('\nSeeding collections...');
    const createdCollections = await Collection.bulkCreate(collections);
    console.log(`  ✓ Created ${createdCollections.length} collections`);

    // Link some restaurants to collections
    const collectionMapping = {
      0: [2, 6, 9, 14, 17],      // Newly Opened
      1: [0, 2, 3, 7, 11, 4],    // Trending  
      2: [2, 5, 6, 9, 17],       // Best Cafes
      3: [3, 7, 16, 8],          // Street Food
      4: [1, 11, 15, 17],        // Romantic
      5: [4, 10, 19],            // Best Biryani
      6: [3, 7, 8, 13, 14, 18],  // Budget Eats
      7: [2, 9, 1, 15],          // Rooftop
    };

    for (const [collIdx, restIdxArr] of Object.entries(collectionMapping)) {
      const collection = createdCollections[parseInt(collIdx)];
      if (collection) {
        for (const rIdx of restIdxArr) {
          if (createdRestaurants[rIdx]) {
            try {
              await collection.addRestaurant(createdRestaurants[rIdx]);
            } catch { /* ignore duplicate */ }
          }
        }
      }
    }
    console.log('  ✓ Linked restaurants to collections');

    // === SEED OFFERS ===
    console.log('\nSeeding offers...');
    const offers = [
      { restaurantId: createdRestaurants[0].id, code: 'WELCOME50', title: '50% OFF up to ₹100', description: 'On your first order', discountType: 'percentage', discountValue: 50, minOrderValue: 199, maxDiscount: 100, isActive: true },
      { restaurantId: createdRestaurants[1].id, code: 'FLAT150', title: 'Flat ₹150 OFF', description: 'On orders above ₹599', discountType: 'flat', discountValue: 150, minOrderValue: 599, maxDiscount: 150, isActive: true },
      { restaurantId: createdRestaurants[2].id, code: 'PIZZA30', title: '30% OFF on Pizzas', description: 'On all pizza orders', discountType: 'percentage', discountValue: 30, minOrderValue: 299, maxDiscount: 120, isActive: true },
      { restaurantId: createdRestaurants[3].id, code: 'CHAAT20', title: '20% OFF', description: 'On orders above ₹100', discountType: 'percentage', discountValue: 20, minOrderValue: 100, maxDiscount: 50, isActive: true },
      { restaurantId: createdRestaurants[4].id, code: 'BIRYANI', title: 'Free delivery', description: 'Free delivery on biryani orders', discountType: 'flat', discountValue: 40, minOrderValue: 249, maxDiscount: 40, isActive: true },
      { restaurantId: createdRestaurants[7].id, code: 'DEENA25', title: '25% OFF', description: 'On your first order from Deena', discountType: 'percentage', discountValue: 25, minOrderValue: 80, maxDiscount: 50, isActive: true },
      { restaurantId: createdRestaurants[11].id, code: 'KEBAB100', title: 'Flat ₹100 OFF', description: 'On orders above ₹499', discountType: 'flat', discountValue: 100, minOrderValue: 499, maxDiscount: 100, isActive: true },
      { restaurantId: createdRestaurants[16].id, code: 'SWEET10', title: '10% OFF on Sweets', description: 'On all sweet orders', discountType: 'percentage', discountValue: 10, minOrderValue: 150, maxDiscount: 50, isActive: true },
      { restaurantId: createdRestaurants[5].id, code: 'CAFE40', title: '40% OFF up to ₹80', description: 'On coffee and cake combos', discountType: 'percentage', discountValue: 40, minOrderValue: 199, maxDiscount: 80, isActive: true },
      { restaurantId: createdRestaurants[10].id, code: 'BIRYANI60', title: '60% OFF up to ₹120', description: 'New user offer on biryani', discountType: 'percentage', discountValue: 60, minOrderValue: 199, maxDiscount: 120, isActive: true },
    ];

    const now = new Date();
    const offersWithDates = offers.map((o) => ({
      ...o,
      validFrom: now,
      validTo: new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000), // 90 days
    }));
    await Offer.bulkCreate(offersWithDates);
    console.log(`  ✓ Created ${offers.length} offers`);

    // === SEED USERS ===
    console.log('\nSeeding users...');

    // Use plain passwords — the User model's beforeCreate hook will hash them
    const [ownerUser] = await User.findOrCreate({
      where: { email: 'owner@momato.com' },
      defaults: {
        name: 'Rahul Sharma',
        email: 'owner@momato.com',
        phone: '9876500001',
        password: 'owner123',
        role: 'owner',
      },
    });
    console.log(`  ✓ Owner user: ${ownerUser.email} (id=${ownerUser.id})`);

    const [customerUser] = await User.findOrCreate({
      where: { email: 'customer@momato.com' },
      defaults: {
        name: 'Priya Verma',
        email: 'customer@momato.com',
        phone: '9876500002',
        password: 'user123',
        role: 'user',
      },
    });
    console.log(`  ✓ Customer user: ${customerUser.email} (id=${customerUser.id})`);

    const [adminUser] = await User.findOrCreate({
      where: { email: 'admin@momato.com' },
      defaults: {
        name: 'Admin',
        email: 'admin@momato.com',
        phone: '9876500000',
        password: 'admin123',
        role: 'admin',
      },
    });
    console.log(`  ✓ Admin user: ${adminUser.email} (id=${adminUser.id})`);

    // === ASSIGN RESTAURANTS TO OWNER ===
    console.log('\nAssigning restaurants to owner...');
    for (const r of createdRestaurants) {
      await r.update({ ownerId: ownerUser.id });
    }
    console.log(`  ✓ Assigned ${createdRestaurants.length} restaurants to owner`);

    // === SEED REVIEWS ===
    console.log('\nSeeding reviews...');
    const reviewTexts = [
      { rating: 5, text: 'Amazing food! Best in Varanasi. Will definitely come back.' },
      { rating: 4, text: 'Great taste and nice ambiance. Service could be a bit faster.' },
      { rating: 5, text: 'Absolutely loved the food here. Highly recommended!' },
      { rating: 3, text: 'Decent food but nothing extraordinary. Average experience.' },
      { rating: 4, text: 'Good quality food with reasonable prices. Nice place for family dining.' },
      { rating: 5, text: 'The best dining experience in the city! Every dish was perfect.' },
      { rating: 4, text: 'Loved the variety in menu. Will visit again for sure.' },
      { rating: 3, text: 'Food was okay. Quantity is good for the price.' },
      { rating: 5, text: 'Superb flavors! Authentic taste that reminds me of home cooking.' },
      { rating: 4, text: 'Nice cozy place with great food. Perfect for a weekend meal.' },
    ];
    const reviewData = [];
    for (let i = 0; i < createdRestaurants.length; i++) {
      const numReviews = 2 + Math.floor(Math.random() * 3); // 2-4 reviews per restaurant
      for (let j = 0; j < numReviews; j++) {
        const rv = reviewTexts[(i + j) % reviewTexts.length];
        reviewData.push({
          userId: customerUser.id,
          restaurantId: createdRestaurants[i].id,
          rating: rv.rating,
          comment: rv.text,
        });
      }
    }
    await Review.bulkCreate(reviewData);
    console.log(`  ✓ Created ${reviewData.length} reviews`);

    // === SEED ORDERS ===
    console.log('\nSeeding orders...');
    const statuses = ['placed', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'delivered', 'delivered'];
    const paymentMethods = ['cod', 'upi', 'card'];
    const addresses = [
      'B-12, Lanka, Varanasi 221005',
      'A-45, Sigra Main Road, Varanasi 221010',
      'D-7, Assi Ghat Road, Varanasi 221005',
      'C-22, BHU Campus, Varanasi 221005',
      'F-9, Cantt Area, Varanasi 221002',
    ];

    // Fetch all menu items for creating realistic orders
    const allMenuItems = await MenuItem.findAll();
    const menuByRestaurant = {};
    allMenuItems.forEach(mi => {
      if (!menuByRestaurant[mi.restaurantId]) menuByRestaurant[mi.restaurantId] = [];
      menuByRestaurant[mi.restaurantId].push(mi);
    });

    const orderData = [];
    for (let i = 0; i < Math.min(createdRestaurants.length, 15); i++) {
      const rid = createdRestaurants[i].id;
      const items = menuByRestaurant[rid] || [];
      if (items.length === 0) continue;

      const numOrders = 1 + Math.floor(Math.random() * 3); // 1-3 orders per restaurant
      for (let j = 0; j < numOrders; j++) {
        // Pick 1-3 random items
        const orderItems = [];
        const itemCount = 1 + Math.floor(Math.random() * 3);
        for (let k = 0; k < itemCount; k++) {
          const mi = items[Math.floor(Math.random() * items.length)];
          const qty = 1 + Math.floor(Math.random() * 2);
          orderItems.push({
            menuItemId: mi.id,
            name: mi.name,
            price: mi.price,
            quantity: qty,
            image: mi.image || null,
          });
        }
        const total = orderItems.reduce((s, it) => s + it.price * it.quantity, 0);

        orderData.push({
          userId: customerUser.id,
          restaurantId: rid,
          items: orderItems,
          totalAmount: total,
          status: statuses[Math.floor(Math.random() * statuses.length)],
          deliveryAddress: addresses[Math.floor(Math.random() * addresses.length)],
          paymentMethod: paymentMethods[Math.floor(Math.random() * paymentMethods.length)],
          paymentStatus: 'paid',
          createdAt: new Date(Date.now() - Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000)),
        });
      }
    }
    await Order.bulkCreate(orderData);
    console.log(`  ✓ Created ${orderData.length} orders`);

    // === SEED RESERVATIONS ===
    console.log('\nSeeding reservations...');
    const reservationStatuses = ['pending', 'confirmed', 'confirmed', 'completed', 'completed'];
    const reservationData = [];
    const dineInRestaurants = createdRestaurants.filter(r => r.hasDineIn);
    for (let i = 0; i < Math.min(dineInRestaurants.length, 10); i++) {
      const r = dineInRestaurants[i];
      const daysAhead = Math.floor(Math.random() * 14) - 3; // some past, some future
      const d = new Date();
      d.setDate(d.getDate() + daysAhead);
      const dateStr = d.toISOString().slice(0, 10);
      const hours = ['12:00', '13:00', '14:00', '18:00', '19:00', '20:00', '21:00'];

      reservationData.push({
        userId: customerUser.id,
        restaurantId: r.id,
        date: dateStr,
        time: hours[Math.floor(Math.random() * hours.length)],
        partySize: 2 + Math.floor(Math.random() * 5),
        status: reservationStatuses[Math.floor(Math.random() * reservationStatuses.length)],
        guestName: customerUser.name,
        guestPhone: customerUser.phone,
        specialRequests: i % 3 === 0 ? 'Window seat preferred' : null,
      });
    }
    await Reservation.bulkCreate(reservationData);
    console.log(`  ✓ Created ${reservationData.length} reservations`);

    console.log('\n========================================');
    console.log('  DATABASE SEEDED SUCCESSFULLY!');
    console.log('========================================');
    console.log(`  Owner:        ${ownerUser.email} / owner123`);
    console.log(`  Customer:     ${customerUser.email} / user123`);
    console.log(`  Restaurants:  ${createdRestaurants.length}`);
    console.log(`  Menu Items:   ${totalMenuItems}`);
    console.log(`  Collections:  ${createdCollections.length}`);
    console.log(`  Offers:       ${offers.length}`);
    console.log(`  Reviews:      ${reviewData.length}`);
    console.log(`  Orders:       ${orderData.length}`);
    console.log(`  Reservations: ${reservationData.length}`);
    console.log('========================================\n');

    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error.message);
    console.error(error);
    process.exit(1);
  }
};

seedData();
